"""uploads path

Revision ID: 16b4ea34ad66
Revises: 9ef04203ef20
Create Date: 2021-06-13 18:28:49.059876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b4ea34ad66'
down_revision = '9ef04203ef20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploads_path', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_avatar')
        batch_op.create_index(batch_op.f('ix_user_avatar_file'), ['avatar_file'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_uploads_path'), ['uploads_path'], unique=True)
        batch_op.drop_column('avatar')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploads_path', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_worker_avatar_file'), ['avatar_file'], unique=True)
        batch_op.create_index(batch_op.f('ix_worker_uploads_path'), ['uploads_path'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_uploads_path'))
        batch_op.drop_index(batch_op.f('ix_worker_avatar_file'))
        batch_op.drop_column('avatar_file')
        batch_op.drop_column('uploads_path')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_uploads_path'))
        batch_op.drop_index(batch_op.f('ix_user_avatar_file'))
        batch_op.create_index('ix_user_avatar', ['avatar'], unique=False)
        batch_op.drop_column('avatar_file')
        batch_op.drop_column('uploads_path')

    # ### end Alembic commands ###
