"""examination table

Revision ID: 326f16a2adbb
Revises: 77b39466b319
Create Date: 2021-05-27 07:24:43.065254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326f16a2adbb'
down_revision = '77b39466b319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_presure', sa.String(length=10), nullable=True),
    sa.Column('alcohol_level', sa.String(length=10), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examination')
    # ### end Alembic commands ###
