"""added columns

Revision ID: 4d818be2aaa8
Revises: 7cd16a694073
Create Date: 2021-06-14 02:55:38.528731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d818be2aaa8'
down_revision = '7cd16a694073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_company_phone'), ['phone'], unique=False)

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('clinic', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_doctor_clinic'), ['clinic'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_phone'), ['phone'], unique=False)

    with op.batch_alter_table('examination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pulse', sa.Integer(), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_worker_license'), ['license'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_license'))
        batch_op.drop_column('birth')
        batch_op.drop_column('license')

    with op.batch_alter_table('examination', schema=None) as batch_op:
        batch_op.drop_column('pulse')
        batch_op.drop_column('temperature')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_phone'))
        batch_op.drop_index(batch_op.f('ix_doctor_middle_name'))
        batch_op.drop_index(batch_op.f('ix_doctor_clinic'))
        batch_op.drop_column('clinic')
        batch_op.drop_column('phone')
        batch_op.drop_column('middle_name')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_phone'))
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
