"""company table

Revision ID: 4fb7f7baf29d
Revises: 
Create Date: 2021-05-21 19:35:32.168566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb7f7baf29d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
