"""added user table

Revision ID: 66b0ef77deb5
Revises: b28e1b5176da
Create Date: 2021-05-24 19:10:05.947764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b0ef77deb5'
down_revision = 'b28e1b5176da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_company_email', table_name='company')
    op.create_foreign_key(None, 'company', 'user', ['id'], ['id'])
    op.drop_column('company', 'email')
    op.drop_column('company', 'password_hash')
    op.drop_index('ix_doctor_email', table_name='doctor')
    op.drop_index('ix_doctor_username', table_name='doctor')
    op.create_foreign_key(None, 'doctor', 'user', ['id'], ['id'])
    op.drop_column('doctor', 'email')
    op.drop_column('doctor', 'username')
    op.drop_column('doctor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('doctor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('doctor', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.create_index('ix_doctor_username', 'doctor', ['username'], unique=False)
    op.create_index('ix_doctor_email', 'doctor', ['email'], unique=False)
    op.add_column('company', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('company', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_index('ix_company_email', 'company', ['email'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
