"""worker table changes

Revision ID: 77b39466b319
Revises: d32627266ddf
Create Date: 2021-05-27 05:05:57.698650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b39466b319'
down_revision = 'd32627266ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_worker_email')
        batch_op.create_index(batch_op.f('ix_worker_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_middle_name'), ['middle_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_middle_name'))
        batch_op.drop_index(batch_op.f('ix_worker_email'))
        batch_op.create_index('ix_worker_email', ['email'], unique=False)
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
