"""empty message

Revision ID: 7cd16a694073
Revises: 16b4ea34ad66
Create Date: 2021-06-13 19:02:04.488633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd16a694073'
down_revision = '16b4ea34ad66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_avatar_file')
        batch_op.create_index(batch_op.f('ix_user_avatar_file'), ['avatar_file'], unique=False)

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index('ix_worker_avatar_file')
        batch_op.create_index(batch_op.f('ix_worker_avatar_file'), ['avatar_file'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_avatar_file'))
        batch_op.create_index('ix_worker_avatar_file', ['avatar_file'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatar_file'))
        batch_op.create_index('ix_user_avatar_file', ['avatar_file'], unique=False)

    # ### end Alembic commands ###
