"""unread exams count

Revision ID: 7f801cfec932
Revises: 8283c7ab09eb
Create Date: 2021-06-09 16:43:46.176735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f801cfec932'
down_revision = '8283c7ab09eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_exams', sa.Integer(), nullable=True))
        batch_op.drop_column('unread_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('unread_exams')

    # ### end Alembic commands ###
