"""change name

Revision ID: b28e1b5176da
Revises: b9a04f44b800
Create Date: 2021-05-22 18:39:38.573260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28e1b5176da'
down_revision = 'b9a04f44b800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('ix_company_company_name', table_name='company')
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.drop_column('company', 'company_name')
    op.add_column('doctor', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('doctor', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('doctor', sa.Column('second_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_doctor_doctor_name', table_name='doctor')
    op.drop_index('ix_doctor_doctor_surname', table_name='doctor')
    op.create_index(op.f('ix_doctor_first_name'), 'doctor', ['first_name'], unique=False)
    op.create_index(op.f('ix_doctor_second_name'), 'doctor', ['second_name'], unique=False)
    op.drop_column('doctor', 'doctor_name')
    op.drop_column('doctor', 'doctor_surname')
    op.add_column('worker', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('worker', sa.Column('second_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_worker_worker_name', table_name='worker')
    op.drop_index('ix_worker_worker_surname', table_name='worker')
    op.create_index(op.f('ix_worker_first_name'), 'worker', ['first_name'], unique=False)
    op.create_index(op.f('ix_worker_second_name'), 'worker', ['second_name'], unique=False)
    op.drop_column('worker', 'worker_name')
    op.drop_column('worker', 'worker_surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('worker_surname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('worker', sa.Column('worker_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_worker_second_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_first_name'), table_name='worker')
    op.create_index('ix_worker_worker_surname', 'worker', ['worker_surname'], unique=False)
    op.create_index('ix_worker_worker_name', 'worker', ['worker_name'], unique=False)
    op.drop_column('worker', 'second_name')
    op.drop_column('worker', 'first_name')
    op.add_column('doctor', sa.Column('doctor_surname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('doctor', sa.Column('doctor_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_doctor_second_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_first_name'), table_name='doctor')
    op.create_index('ix_doctor_doctor_surname', 'doctor', ['doctor_surname'], unique=False)
    op.create_index('ix_doctor_doctor_name', 'doctor', ['doctor_name'], unique=False)
    op.drop_column('doctor', 'second_name')
    op.drop_column('doctor', 'first_name')
    op.drop_column('doctor', 'password_hash')
    op.add_column('company', sa.Column('company_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.create_index('ix_company_company_name', 'company', ['company_name'], unique=False)
    op.drop_column('company', 'name')
    # ### end Alembic commands ###
