"""worker table

Revision ID: b322e6362f61
Revises: 4fb7f7baf29d
Create Date: 2021-05-21 19:47:37.203492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b322e6362f61'
down_revision = '4fb7f7baf29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_surname', sa.String(length=64), nullable=True),
    sa.Column('worker_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_email'), 'worker', ['email'], unique=True)
    op.create_index(op.f('ix_worker_worker_name'), 'worker', ['worker_name'], unique=False)
    op.create_index(op.f('ix_worker_worker_surname'), 'worker', ['worker_surname'], unique=False)
    op.drop_index('ix_company_company_name', table_name='company')
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.create_index('ix_company_company_name', 'company', ['company_name'], unique=False)
    op.drop_index(op.f('ix_worker_worker_surname'), table_name='worker')
    op.drop_index(op.f('ix_worker_worker_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_email'), table_name='worker')
    op.drop_table('worker')
    # ### end Alembic commands ###
