"""doctor table

Revision ID: b9a04f44b800
Revises: b322e6362f61
Create Date: 2021-05-22 02:29:59.649407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a04f44b800'
down_revision = 'b322e6362f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('doctor_surname', sa.String(length=64), nullable=True),
    sa.Column('doctor_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_doctor_name'), 'doctor', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_doctor_doctor_surname'), 'doctor', ['doctor_surname'], unique=False)
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_username'), 'doctor', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_username'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_doctor_surname'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_doctor_name'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
