"""strange error

Revision ID: e7a68aeb495a
Revises: a4795a13d897
Create Date: 2021-05-30 23:22:03.899973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a68aeb495a'
down_revision = 'a4795a13d897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=140), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index('ix_doctor_email')
        batch_op.drop_index('ix_doctor_username')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_worker_email')
        batch_op.create_index(batch_op.f('ix_worker_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_middle_name'), ['middle_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_middle_name'))
        batch_op.drop_index(batch_op.f('ix_worker_email'))
        batch_op.create_index('ix_worker_email', ['email'], unique=False)
        batch_op.drop_column('middle_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_column('role')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_doctor_username', ['username'], unique=False)
        batch_op.create_index('ix_doctor_email', ['email'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
