"""error in examination table

Revision ID: f525e6961be9
Revises: 326f16a2adbb
Create Date: 2021-05-27 08:07:16.306499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f525e6961be9'
down_revision = '326f16a2adbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_pressure', sa.String(length=10), nullable=True))
        batch_op.drop_column('blood_presure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_presure', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('blood_pressure')

    # ### end Alembic commands ###
